name: junction_frame
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  async_redux: ^24.0.2
  camera: ^0.11.0+2
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  go_router: ^14.4.1
  graphql_flutter: ^5.2.0-beta.7
  image_picker: ^1.1.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
